---
name: Terraform

on:
  push:
    branches:
      - main
  workflow_call:

concurrency: terraform

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Run terraform
        uses: ./github/workflows/tf-action