---
name: Terraform

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Init
        run: terraform init
      
      - name: Check
        run: terraform fmt -check
      
      - name: Plan
        run: terraform plan -input=false -out=tfplan.out
      
      - name: Apply
        run: terraform apply -input=false tfplan.out